### ISSUE TITLE
Sync tags & minimal patch download URLs

### ISSUE THREAD

**Issue by haampie** [JuliaLang/libuv#20]
This is a bit of a trivial request, but it'd be nice if compare urls worked using tags:

https://github.com/JuliaLang/libuv/compare/v1.42.0...julia-uv2-1.42.0.patch

The tags here are old: https://github.com/JuliaLang/libuv/tags

**Comment by DilumAluthge** [comment]
@vtjnash ^

**Comment by vtjnash** [comment]
Not a bad idea! Note that you currently just need to give the fully-qualified name of the tags and it works already:
https://github.com/libuv/libuv/compare/master...JuliaLang:julia-uv2-1.42.0.patch

**Comment by haampie** [comment]
Right, I think my question is rather: can I get a URL with a minimal patch of `julia-uv2-1.42.0` on top of the actual commit tagged 1.42.0. And right now it seems not really possible, I think because the `julia-uv2-1.42.0` branch was merged from wherever 1.42.0 was tagged.

E.g. https://github.com/libuv/libuv/compare/v1.42.0...JuliaLang:julia-uv2-1.42.0.patch includes commits from 2014 :p and it does not apply cleanly

**Comment by vtjnash** [comment]
juulia-uv2-1.42.0 was branched from v2, aka master

**Comment by haampie** [comment]
Ok, would it make sense to branch from `v1.x` so that git history is linear from the tagged commit?

**Comment by vtjnash** [comment]
no, linear history is pretty useless of a concept

**Comment by haampie** [comment]
sure, but for packaging it would be nice to have simpler patches

```
$ git diff --shortstat 4fe755bc5b98981ef5f58879f5f581d1c10874b6..julia-uv2-1.42.0~2
 26 files changed, 626 insertions(+), 484 deletions(-)

$ git diff --shortstat v1.42.0..julia-uv2-1.42.0~2
 132 files changed, 3562 insertions(+), 3195 deletions(-)
```
